### ISSUE TITLE
Markbot will not finish processing dinosaur-designs

### ISSUE THREAD

**Issue by Jowens96** [Jowens96/dinosaur-designs#1]
Everything has a green check mark and seems alright, but the screenshots section will not load. It is displays INDEX.HTML: 320PX with a rotating gear indicating that it's processing. I've left it for about ten minutes maximum but it doesn't complete. Encountered the issue on Monday and have tried to submit a few more times since then. I was able to submit other assignments through markbot with no problem.

![image](https://user-images.githubusercontent.com/31851871/31232716-a63461b4-a9b8-11e7-8aa2-b466b9f55161.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
I'm not sure exactly what the problem is—but have you checked out the index.html in the browser? It looks quite different than the screenshot.
